title: Cynthia Maria Garcia # your name (or website title) here
logo: "/images/profile.JPG"
description: > # your text below (remove <br> elements if you don't need line breaks)
  About me: I'm currently working at Intel and graduated ASU with a BS in Computer Science (Software Engineering)
  I have interests in programming and technical communication as well as UX design!
  <br><br>
 
  
theme: jekyll-theme-minimal

